---
  - hosts: instance
    gather_facts: yes
    become: true
    tasks:

      - name: Install python
        raw: "test -e /usr/bin/python || (apt-get install -y python)"
        args:
          executable: /bin/bash

      - name: Add docker's official GPG key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add docker repository
        apt_repository:
          repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
          update_cache: yes

      - name: Update and upgrade packages
        apt:
          update_cache: yes
          upgrade: dist

      - name: Install docker-ce and it's dependencies
        apt:
          name: "{{ item }}"
          state: present
        with_items:
          - docker-ce
          - thin-provisioning-tools
          - lvm2

      - name: Stop docker service
        service:
          name: docker
          state: stopped

      - name: Populate daemon.json
        template:
          src: "daemon.json.j2"
          dest: /etc/docker/daemon.json

      - name: Start docker servuce
        service:
          name: docker
          state: started
