---
  - name: Get Droplet info
    uri:
      body_format: json
      url: "https://api.digitalocean.com/v2/droplets"
      method: GET
      headers:
        Content-Type: 'application/json'
        Authorization: "Bearer {{ do_api_token }}"
      return_content: yes
    register: do_droplet_info

  - name: Get Droplet id
    set_fact:
      do_droplet_id: "{{ item.id }}"
    with_items:
      - "{{do_droplet_info.json.droplets}}"
    when: "item.name == do_droplet_name"

  - block:

    - name: Create block storage
      digital_ocean_block_storage:
        block_size: "{{ do_volume_size }}"
        command: create
        oauth_token: "{{ do_api_token }}"
        region: "{{ do_region_id }}"
        state: present
        volume_name: "{{ do_volume_name }}-{{ do_region_id }}"

    - name: Attach block storage to droplet
      digital_ocean_block_storage:
        command: attach
        droplet_id: "{{ do_droplet_id }}"
        oauth_token: "{{ do_api_token }}"
        region: "{{ do_region_id }}"
        state: present
        volume_name: "{{ do_volume_name }}-{{ do_region_id }}"

    when: do_volume_remove|default(False)|bool == False

  - block:

    - name: Detach block storage from droplet
      digital_ocean_block_storage:
        command: attach
        droplet_id: "{{ do_droplet_id }}"
        oauth_token: "{{ do_api_token }}"
        region: "{{ do_region_id }}"
        state: absent
        volume_name: "{{ do_volume_name }}-{{ do_region_id }}"
      when: "do_droplet_id is defined"

    - name: Remove block storage
      digital_ocean_block_storage:
        command: create
        oauth_token: "{{ do_api_token }}"
        region: "{{ do_region_id }}"
        state: absent
        volume_name: "{{ do_volume_name }}-{{ do_region_id }}"

    when: do_volume_remove|default(False)|bool == True