docker_compose_validate: true
docker_compose_file_path: "/etc/docker-compose/docker-compose.yml"
jenkins_compose_config:
  version: '3'
  services:
    jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins
      user: jenkins
      volumes:
        - jenkins_home:/var/jenkins_home
        - jenkins_data:/jenkins_config
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - "127.0.0.1:80:8080"
  volumes:
    jenkins_data:
      driver: local
    jenkins_home:
      driver: local