digitalocean:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    do_api_token: 4d22a74b6a4bcbddcaca56706b4075d11b2134b7d3102d372ab147da0d1d5031
    do_image_id: ubuntu-18-04-x64
    # this name will be using also as subdomain for do_domain_name
    # droplet name will be combined together with do_domain_name
    do_droplet_name: claire
    do_private_networking: true
    # delete Floating IP after droplet deletion
    do_fip_delete: false
    do_region_id: fra1
    do_size_id: s-1vcpu-1gb
    # use user-data from template
    do_user_data: true
    # volume size in Gigabytes
    # you can delete the line if you don't want to use volumes
    # do_volume_size: 5
    # do_droplet_name, do_volume_name and do_region_id will be used as volume name
    # you can delete the line if you don't want to use volumes
    # do_volume_name: volume01
    # delete the line below if you don't want to use domains
    do_domain_name: rand.net.ua
    # use with caution, it will delete domain with all subdomains if true
    do_domain_delete: false
    do_firewall:
      - direction: inbound_rules
        proto: icmp
        sources:
          addresses: 0.0.0.0/0
      - direction: inbound_rules
        proto: tcp
        ports: 22
        sources:
          addresses: 0.0.0.0/0
      - direction: inbound_rules
        proto: tcp
        ports: 80
        sources:
          addresses: 0.0.0.0/0
      - direction: inbound_rules
        proto: tcp
        ports: 443
        sources:
          addresses: 0.0.0.0/0
      - direction: outbound_rules
        proto: icmp
        destinations:
          addresses: 0.0.0.0/0
      - direction: outbound_rules
        proto: tcp
        ports: all
        destinations:
          addresses: 0.0.0.0/0
      - direction: outbound_rules
        proto: udp
        ports: all
        destinations:
          addresses: 0.0.0.0/0
